### ISSUE TITLE
Backend Interoperability

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#437] opened 2019-12-24 16:17 UTC
**BLUF**: A common data layout and optional backend specific versions of the `*Apply` functions would improve backend interoperability and provide consistent user facing behavior.

**Issue**: Inconsistent data layouts are complicating interoperability and the fallback mechanism for advanced operator functionality. Also, user facing functions currently provide inconsistent behavior in some cases.

**Proposal**:
 - Functions in `ceed.h` use a common data layout
 - New backend specific functions in `ceed-backed.h` use backend specific data layout

**Example**:
 - Functions such as `CeedElemRestrictionApply` use the common Evector layout `[elem, component, node]` and Qvector layout `[elem, component, qpt]`
 - Functions such as `CeedElemRestrictionApplyBackend` are free to use backend specific Evector/Qvector layouts

**Test**:
 We can test interoperability by using ceed objects and qdata provided by any backend in a `/cpu/self/ref/serial` operator
```
Ceed ceedref, ceedtest;

CeedInit("/cpu/self/ref/serial", &ceedref);
CeedInit("whateveryoulike", &ceedtest);

// Build Vectors, Bases, Restrictions in ceedtest

// Build identical operators/qfunctions in ceedref and ceedtest using above objects
CeedOperatorCreate(ceedtest, qf_qdata, CEED_QFUNCTION_NONE, CEED_QFUNCTION_NONE, &op_qdata);

CeedOperatorCreate(ceedtest, qf_apply_test, CEED_QFUNCTION_NONE, CEED_QFUNCTION_NONE, &op_apply_test);
CeedOperatorCreate(ceedref, qf_apply_ref, CEED_QFUNCTION_NONE, CEED_QFUNCTION_NONE, &op_apply_ref);
...

// Build Qdata
CeedOperatorApply(op_qdata, x, qdata, CEED_REQUEST_IMMEDIATE);

// Test Interoperability
CeedOperatorApply(op_apply_test, u, v1, CEED_REQUEST_IMMEDIATE);
CeedOperatorApply(op_apply_ref, u, v2, CEED_REQUEST_IMMEDIATE);

// Check v1 == v2
```

**Current Interoporability**:
 - Vector: Good (host pointers only)
 - Basis: Good for single elements (multiple elements should be backend specific)
 - Restriction: Problem with Evector/Qvector layouts
 - QFunction: Should be backend specific, but easy to clone/fallback
 - Operator: Composition of above

**Additional**:
 - See discussion in #425, CUDA qdata (so also MAGMA and soon also OCCA qdata) would need to be permuted
 - Blocked restrictions are not necessarily intended for users and might belong in `ceed-backend.h` in this proposal
 - We should document that multi-element basis action is backend specific behavior. We might wish to put single element basis apply in `ceed.h` and multiple element basis action in `ceed-backend.h`
- This would provide a way to test backend logic for operators that wish to use alternate restrictions, see discussion in #424 
 - This would offer `AssembleLinearQF`, `AssembleLinearDiagonal`, `CreateFDMElementInverse`, and future `AssembleQF`, `AssembleDiagonal`, `AssembleElements` (or whatever we call these) to all backend via fallback
 - We should also fix accessing other backend's data, such as blocked/opt using `include "../ref/ceed-ref.h''` to access restriction indices

**Comment by jeremylt** [comment] 2019-12-30 19:27
I think the hard part is the `qdata` vectors (or any other case when we are applying `CEED_BASIS_NONE` and an identity restriction). The default impl I'm proposing would need those vectors to have [elem, comp, qpoint], but I think for the GPU those vectors are stored [comp, elem, qpoint] or something like that.

This difference means that we would need different behavior on the GPU side for an identity restriction applied to an lvector, like `xcords` and a qvector, like `qdata`.

**Comment by nbeams** [comment] 2020-01-13 17:38
I'm a bit confused by the example test idea.  If the two backends are allowed to use different Q-Vector layouts, how can they use the same qdata input?  Maybe I'm not understanding what you're proposing for the test.

Regarding the Q-Vector layouts for CUDA (and thus MAGMA), they are currently:
`[ (dimension), component, element, qpoint ]` 
where the first index is outermost, qpoint is innermost, and dimension is in parentheses because it's only present when dealing with the gradient.

Having dimension and component on the outside allows the CUDA backends to evalute the Qfunction for multiple elements at once without changing how the user-provided QFunctionUser is written; you only have to give `numelem * Q` as the `Q` parameter when calling `CeedQFunctionApply` inside the Operator.  If the elements and qpoints were not "together" on the inside of the Q-Vector, this wouldn't work correctly. (@YohannDudouit can correct me if I'm wrong about any of this.)

After looking at the CUDA code this way, I was confused about how the blocked and opt CPU backends handle multiple elements if they have a `[ element, (dimension), component, qpoint]` layout as mentioned.  I noticed the `QFunctionApply` call in the Operator codes had `Q*blksize` as the `Q` parameter, with `blksize` being a number of elements, so essentially the same call as in the CUDA backends.  (Here, @jeremylt can correct me if I'm wrong.)  But the QFunctionUser wouldn't work correctly with this value for Q if the data layout is with elements as outer index.  However, after looking at the Basis funtions some more from the cpu/ref backend, I think the Q-Vector layout is actually 
`[ (dimension), component, qpoint, element ]` 
with element as *innermost* index instead of outermost.  This *does* allow multiple elements in a single QFunction call, as the blocked and opt backends use.

In light of this, it seems there are only two reasonable Q-Vector layouts possible.  Would it be worth just picking one and making all backends use it?

Alternatively, would it be worth defining a common way of referring to a set of possible data layouts (with definitions like the CEED_EVAL modes or something, giving names to layouts) and have one set of backend functions like `QVectorReorder` and `EVectorReorder` which could take a specific desired data layout definition as a parameter. Otherwise, some backends might end up having to have two versions of pretty much every function.   I believe this is what was proposed in #425?  Was this idea dropped due to some offline discussions I don't know about?  I also think it's worth discussing simply storing stride information in a unified way so top-level functions could access any portion of any vector (qpoints in an element, components, etc.) without reordering, but I'm obviously biased because I proposed that in #425 as well.

**Comment by YohannDudouit** [comment] 2020-01-13 18:02
@jeremylt Can you provide your data layout at quadrature points? I'm a bit confused by what @nbeams wrote.

**Comment by jeremylt** [comment] 2020-01-13 18:11
We use [(derivative), component, qpoint, element] (blocked element processing) or [(derivative), component, qpoint] (serial element processing).

**Comment by YohannDudouit** [comment] 2020-01-13 19:11
I've been thinking, and I'm not sure that the real issue is the different data layouts. I think you need to know the "element stride" between the components for the operator you're building, but previously, we didn't have an operator that required to know this, because computations were independent at each quadrature point, so the element index did not matter. I have the impression that this independence of computation at quadrature point (independence relative to elements) does not hold with what you're trying to achieve.

**Comment by jeremylt** [comment] 2020-01-13 19:18
Qfunction assembly, diagonal assembly, and some of the preconditioning work needs to connect data about all the quadrature points on an element.

Right now I can't do that because there is no default data layout at the quadrature points and no way to convert to a standard layout.

We could instead just implement a CPU layout fallback and a GPU layout fallback for these preconditioning functionality. It would mean that half of the backends might be delayed in getting features though, which I'm trying to avoid.

**Comment by YohannDudouit** [comment] 2020-01-13 19:31
I don't understand why diagonal assembly needs more information than other operators, that sounds wrong to me, can you develop a bit? Our implementation in MFEM ( mfem/mfem#982 ) of diagonal assembly uses exactly the same setup as the operator, the apply kernel differs. Unless what you're saying is that backend interoperability is broken in general.
What your blocked backend do doesn't seem to respect the libCEED spec to me, the `Q` stride that goes between components should be enough, but in the case of your blocked backends that doesn't seem to be sufficient if I understand correctly what you're saying.

**Comment by jedbrown** [comment] 2020-01-13 19:35
Thanks, @nbeams. I would be happy with a stride tuple/struct (the unified way to denote layout). Reference code could work with that directly, and vectorized code could specialize on one or more variants. In CPU code, `[(dimension), component, qpoint, element]` is preferred for vectorization (especially at low-moderate degree) because the `element` dimension is chosen to be a small multiple of the hardware vector length.

With respect to elementwise-constant arguments to qfunctions, if their data is small, I prefer just defining a constant space that is mapped to quadrature points via interpolation matrix `B` (a single column of ones). There are scenarios in which the element data is huge compared to everything else, and even where some work could be amortized over the element before evaluating at each quadrature point, but I think we'd be better off to approach that as a composition or indexing extension than to lose the quadrature point independence principle (and thus the ability to swap different vectorization techniques).

**Comment by jeremylt** [comment] 2020-01-13 19:57
@YohannDudouit, you can get more efficient diagonal assembly if you know more about the data layout. Without being able to create an assembled QFunction matrix, it seems like you'd need P**3 element operator evaluations to get the diagonal.

The blocked backends aren't violating any spec. Backends are free to reorder qpoints between elements. Both CPU blocked and GPU code generation backends are reordering qpoints.

**Comment by YohannDudouit** [comment] 2020-01-13 21:03
@jeremylt Are you using a different formula for a mass operator than:
```
diag(M(dx,dy,dz,e)) = sum_qx  B(dx,qx)^2 * (sum_qy B(dy,qy)^2 * (sum_qz B(dz,qz)^2 * D(qx,qy,qz,e)))
```
?
Is it more accurate to say that your data format is `[(dimension), component, element_batch, qpoint, element_in_batch]`?

**Comment by jedbrown** [comment] 2020-01-13 21:11
More like `[{element_batch}, (dimension), component, qpoint, element_in_batch]` where the outermost index is not actually an array but a loop iteration in which a smaller scratch buffer is reused.

**Comment by YohannDudouit** [comment] 2020-01-13 23:00
Then a stride associated with the element index wouldn't work, since this make the access non-linear, no?

**Comment by jedbrown** [comment] 2020-01-13 23:13
I'm not sure of the question. You can't index outside a batch because that memory doesn't exist. Within a batch, it's just the innermost index. The GPU layout is basically the same, but with one large batch (the whole local domain).

**Comment by YohannDudouit** [comment] 2020-01-13 23:42
I thought we were talking about the layout of the `qData`, which exists outside a batch.

**Comment by jeremylt** [comment] 2020-01-13 23:46
All CPU backends use qdata in the format `[element, (dimension), component, qpoint]`, but it is reordered to `[{element batch}, (dimension), component, qpoint, elementInBatch]` by the blocked backends, which may or may not involve permuting the entire qdata vector.

**Comment by jedbrown** [comment] 2020-01-13 23:57
@jeremylt Should we have support implicitly-ordered vectors to avoid this superficial reordering? That is, we often have a setup that computes collocated values and one or more `apply`s that use it. Should we support a representation that allows us to pass these values between `CeedOperator`s without reordering? (Not urgent.)

**Comment by YohannDudouit** [comment] 2020-01-13 23:57
Okay, then maybe that we really have only two layouts, i.e. `[element, (dimension), component, qpt]` and `[(dimension), component, element, qpt]` for the moment. However, I'm confused because I thought my GPU backends already supports these two layouts (prescribed by the `lmode`), so I'm not sure I understand what is not working with interoperability.

**Comment by jeremylt** [comment] 2020-01-14 00:06
> @jeremylt Should we have support implicitly-ordered vectors to avoid this superficial reordering? That is, we often have a setup that computes collocated values and one or more applys that use it. Should we support a representation that allows us to pass these values between CeedOperators without reordering? (Not urgent.)

I think that would be reasonable. In practice, I only reorder the qdata once for a blocked operator and don't permute if the qdata has not been changed, so the impact has been minimal.

> Okay, then maybe that we really have only two layouts, i.e. [element, (dimension), component, qpt] and [(dimension), component, element, qpt] for the moment. However, I'm confused because I thought my GPU backends already supports these two layouts (prescribed by the lmode), so I'm not sure I understand what is not working with interoperability.

The easiest way to see the problem is to try remove
```
ierr = CeedSetBackendFunction(ceed, "Operator", op, "AssembleLinearQFunction",
                                CeedOperatorAssembleLinearQFunction_Cuda);
```
 from the CUDA backends and run the test suite. The `qdata` from CUDA backends is not ordered such that it can be used by the CPU backends to provide default impl of `AssembleLinearQF` and therefore also provide default impl of `AssembleLinearDiag` and `CreateFDMElementInverse`.

**Comment by YohannDudouit** [comment] 2020-01-14 04:19
After discussing deeply with @jeremylt I think we understand better the reasons why interoperability fails. We had a different understanding of which layout is expected from qvectors both as input and output of a `CeedOperator`.
I was treating qvectors, as a special case were lvector=evector=qvector, however I was using the data layout prescribed by the `lmode` both for input and output (`[elem, quad, comp]` or `[comp, elem, quad]`, last being the fastest index).
On the other side, @jeremylt was considering that evector=qvector, thus expecting qvectors in the canonic evector layout (`[elem, comp, quad]`).
So if the number of component is different from 1, then all these layouts are different, and therefore backend interoperability fails (between CPU and GPU).

This also made us realize that we have a different understanding of what an Identity restriction is. For me, it meant that the global (lvector) to local (evector) Restriction does not require an indirection (lvector=evector). Therefore, I was still taking into account the `lmode` to eventually perform a transformation of data layout to suit the needs of my backends. (Identity is therefore not necessarily a NoOp)
For @jeremylt , an Identity restriction also means that lvector=evector, but the data is provided in evector layout (here also this layout is different from the two layouts I was considering), meaning that an Identity restriction is a special case that can be optimized.

Now that the problem is identified (I believe that interoperability will work once it is solved), we need to discuss and agree about the solution.
I mostly see three paths:
- @jeremylt's approach which enables certain optimizations on CPU and the data layout also corresponds to Nek data layout as far as I understood.
- My approach, presents the advantage that the user can inform the backend in which format he is providing the qvector (for a velocity field at quadrature point for instance), but Nek wouldn't be able to provide its qvector directly with this it seems.
- We combine both approaches and let `lmode` have three values corresponding to three data layouts described that we seem to be encountered in either MFEM or Nek. We could consider a "default" value for `lmode` to let backends output in their favorite layout during the Setup and input for the Apply, but that might be early optimization at this point.
(And we also need to clarify the role of the Identity restriction.)

Tell me what you think.

PS: Some of the things I wrote about @jeremylt's intent might be inaccurate.

**Comment by jeremylt** [comment] 2020-01-14 05:19
Close for Qdata: I store it in the canonical lvector layout [elem, comp, pt], but it may be reordered as needed for performance for blocked backends an individual blocks are restricted to the qvector.

One way or another, I'd like to be able to run qdata generated in one backend inside the ref serial backend. This requires common behavior for user facing function calls. This will give us initial fallback capability for new development.

**Comment by nbeams** [comment] 2020-01-14 15:58
I'm confused about how `lmode` comes into play with Q-Vectors.  `lmode` only exists for L-Vectors, right?  And as such, is only involved in L- or E-Vectors/ElementRestrictions?  Whereas Q-Vectors come from Basis actions or QFunctions. Thus the Restrictions (Identity or not) and Q-Vectors are completely separate, no?  

I know the qdata can be read as a vector, and often is (when using separate setup and apply Operators) but from the codes I've looked at, that qdata vector was created in a QFunction from Q-Vector inputs, which came from Basis actions.  Is there an example I can look at where the user provides the qdata separate from libCEED and must know the Q-Vector layout to have the proper input?

**Comment by YohannDudouit** [comment] 2020-01-14 17:40
@nbeams  It is also very common to have qvectors to describe physics, for instance a velocity field given at quadrature point, thus the data layout need to be described, this is where `lmode` comes into play. There is examples in [MFEM](https://github.com/mfem/mfem/blob/master/fem/bilininteg_mass.cpp#L74). Any analytical function for instance needs to be evaluated at quadrature point (potentially by an external library), but nothing for libCEED since the problem we're talking about would rise and create a bug, since the different backends treat qvectors differently.

**Comment by jeremylt** [comment] 2020-01-14 18:35
I'm still not sure that it makes sense to use an Identity Restriction to mean anything other than the user has provided an lvector that is in the canonical evector layout, [element, component, node] and maybe a single other permutation.

What data layout is this MFEM data you are referring to? Is it [element, node, component]? Something else?

I'm not wild about the idea of expanding the the list of possible Identity Restrictions past 2. The user can always provide a list of indices for other layouts.

**Comment by nbeams** [comment] 2020-01-14 18:37
Oh, I see.  You mean the restriction created by `CeedElemRestrictionCreateIdentity` would produce the desired Q-Vector layout for the cuda backends, for the `CEED_EVAL_NONE` mode (where the operator is passed in an L-Vector of values).  Hence the direct tie between L-Vectors and Q-Vectors in this case?

**Comment by YohannDudouit** [comment] 2020-01-14 18:40
@jeremylt It does make sense, this is also widely used for Discontinuous Galerkin methods. MFEM data layout can be either of the two described by `lmode`.
I think there is no canonical evector layout, this has been discussed multiple times, the evector layout is up to the backend (the [MAGMA backend](https://github.com/CEED/libCEED/pull/424/files#diff-0568d9adaf936611e066b47f2fc8fe3dR72) has a different one for instance).

@nbeams That's correct.

**Comment by nbeams** [comment] 2020-01-14 19:06
I think part of the problem with what the name "should" mean is exactly why I was confused: that Restrictions usually do one thing (take L-Vectors to E-Vectors) but in the case of passing in external qdata for the qfunction, they do L-Vector to Q-Vector.   But I do think it's rather confusing to have "IdentityRestriction" refer to anything other than exactly what it says on the tin, i.e., an identity operator.  The name implies that when using it, we return the same data as we input, at least to me.

Would it be more clear to have the `CEED_EVAL_NONE` section of `BasisApply` do the reordering in any backends that wish to do so?  These functions are already backend-specific behavior anyway. Would there be any disadvantage compared to doing the reordering in the ElementRestriction? Then it's always the Basis that's doing any E- to Q- vector reordering.

Another option might be to provide some top-level user function for loading external qdata given in L-Vectors.  The user could specify the layout as a parameter and then the backend-specific load function could do whatever it needs to do to create a Q-Vector for that backend.   The resulting input field could use an IdentityRestriction in its "true" sense, where it wouldn't actually change the data.

**Comment by jeremylt** [comment] 2020-01-14 19:07
I don't think we want to specify Qvector layout with an Identity Restrictions. Qvector layout should be backend specific. The user shouldn't know the Qvector layout, as it varies from backend to backend. Expecting the users to provide Qvectors breaks the abstraction as it breaks runtime switching of backends.

There is a canonical evector layout as given by the test suite. Backends are free to use different orderings for performance, but it makes sense to have a canonical ordering for backend interoperability. If all backends support the canonical evector ordering for ElemRestrictionApply and use internal orderings for ElemRestrictionApplyBackend, then I can provide basic implementation of the preconditioning work for all backends.

I think we have two issues:
1) What are the expected lvector layouts for Identity Restrictions for lmode CEED_NOTRANSPOSE and CEED_TRANSPOSE.
Currently:
CEED_NOTRANSPOSE - known [element, component, node] per test suite
CEED_TRANSPOSE - unknown [element, component, node]? not currently tested

2) Would backends be willing to support the canonical layout via ElemRestrictionApply and backend specific layouts via ElemRestictionApplyBackend? I really feel like we need a common layout and backend specific layouts for optimization.

**Comment by YohannDudouit** [comment] 2020-01-14 19:25
@nbeams I don't agree with this at all, it is an identity from the mathematical point of view, but for optimization reasons the backend might reorder the data, but it's still an identity operation. What you are proposing in your last paragraph is what I foresee for the Identity Restriction. The identity means that you don't need an indirection to access the data (because the indirection is the identity), so the data is given in lvector form (like everything else), and reordered (or not) by the backend to be used in the qFunction.

@jeremylt Again, it has been discussed many time that we don't want to force an evector layout as it constrains too much optimization.
1. I don't think this is a good idea to introduce these two new data layouts, I don't see the need for it. The identity restriction should obey to the same layout expectations as a standard restriction.
2. I don't see why we would need this.

**Comment by jeremylt** [comment] 2020-01-14 19:32
1. The behavior of an identity restriction with CEED_NOTRANSPOSE is not new. It is in the test suite.
The behavior of CEED_TRANSPOSE with an identity restriction is currently undefined.

2. It provides backend interoperability if there is a common data layout. Also, user facing interfaces should have predictable behavior.

2.

**Comment by nbeams** [comment] 2020-01-14 20:32
@YohannDudouit I disagree that the "Identity" in the name should refer to the lack of indirection for data access.  The "regular" ElementRestriction can also be created without indirection for the L-Vector (the `indices` array is optional, no?).

@jeremylt if you need the Q-Vectors to be in a certain layout, too, wouldn't we also have to provide two versions of Basis actions (since they produce Q-Vectors)?  My worry is that we start to lose the effectiveness of the test suite, since multiple parts of the Operator would be different than what was tested in the specific tests, so passing t3* tests still wouldn't mean you could rule out your backend-only Basis actions being the source of an Operator error, for example.  Assuming here that the *Backend version of any changed functions would only get used inside that backend's Operators.

For what you need with your preconditioners, how hard would it be to use structs that each backend can define for E-Vectors and Q-Vectors like, for the example of the current cuda Q-Vector layout, 

```
struct VectorLayout {
  CeedInt node_stride;
  CeedInt comp_stride; 
  CeedInt dim_stride; 
  CeedInt el_stride;
}

VectorLayout qvl = { 1, 
                      Q * num_el, 
                      Q * num_el * ncomp,
                      Q };
```

Then any top-level code that's looping through expecting the canonical layout could just do
```
for e = 0; e < num_el; e++
 for c= 0; c < ncomp; c++
   for n = 0; n < Q; n++
   //code for cpu_order_vec[  e * ncomp * Q + c * Q + n ] 
   // uses gpu_order_vec[ n * qvl.node_stride + c * qvl.comp_stride + e * qvl.el_stride];
```
And similar for E-Vectors.  The question would be where this could be stored and how to initialize and access them.  

The ElementRestriction tests could be rewritten to check for any E-Vector layout based on this stride information.

**Comment by jeremylt** [comment] 2020-01-14 21:12
I do not need Qvectors in be in a certain layout. Backends can use any layout. All I need is consistent behavior from `CeedElemRestrictionApply`.

We could do that with a struct stored somewhere. We could also do it by separating `CeedElemRestrictionApply` and `CeedElemRestrictionApplyBackend`. This would provide interoperability and consistent user facing behavior.

**Comment by nbeams** [comment] 2020-01-14 21:29
But `CeedElemRestrictionApply` in the current cuda/ref backend already produces the same output as the cpu backends, that is, `[element, component, node]`.  If the problem is the IdentityRestriction, then how is that not tied to the Q-Vector layout, since its output for cuda is a "cuda-ordered Q-Vector" as `[(dimension), component, element, qpoint]`?  Unless the problem is that the IdentityRestriction isn't an identity operator for the cuda backend, in which case it could be fixed by moving the reordering of E-Vector layout --> Q-Vector layout for `EVAL_NONE` to the BasisApply.

We put in a request to change the E-Vector ordering in the MAGMA backend, so we would still have to make more changes on our side if we stick with that.  It did improve our speed in both tensor and non-tensor, though...

**Comment by jeremylt** [comment] 2020-01-14 21:40
Right, it is my understanding that the identity restriction for CUDA backends means lvector = qvector instead of lvector = evector as I believed.

I want backends to use any qvector and evector ordering internally for performance. I just need a way to get an evector in the canonical ordering for providing a basic implementation so I can provide initial capability for future operator functionality.

**Comment by jeremylt** [comment] 2020-01-15 06:55
Thanks to @YohannDudouit's patience, I think that I understand where the confusion is.

In preparation for the future conference call on this, I will write up how I conceptualize libCEED operators, so everyone knows my language and framing.

I will discuss the reference case and put caveats below and reference the documentation as needed.

For me, the action of a `CeedOperator` always starts with `lvector`s and ends with `lvector`s. All inputs/outputs conceptually trace the decomposition A = G^T B^T D B G.

When `CeedOperatorApply` is called, the following steps occur (logically, if not actually in the case of optimized backends)

0) Inputs are provided as `lvector's (See caveat a)

1) `CeedElemRestrictionApply` is called for all inputs, transforming the `lvector`s to `evector`s (See caveat b, c). Per the documentation, *all* `ElemRestriction`s are a "restriction from local vectors to elements"

2) `CeedBasisApply` is called for all inputs, transforming the `lvector`s to `qvector`s (See caveat b, d)

3) `CeedQFunctionApply` is called, generating output `qvector`s from input `qvector`s

4) `CeedBasisApply` is called for all outputs, transforming the `qvector`s to `evector`s

5) `CeedElemRestrictionApply` is called for all outputs, transforming the `evector`s to `lvector`s

Caveats

a) Some inputs may be provided as `evector`s, using the canonical `evector` format `[element, component, node]`, as described in the test suite. In this case the `ElemRestriction` is Identity. See the Nek5000 examples. The CPU backends currently only support applying `ElemRestriction`s to `lvector`s that have their data in the canonical `evector` format described in the test suite. Any other layout requires a standard `ElemRestriction` to produce the desired results on CPU.

b) Documentation: "A backend may choose to operate incrementally without forming explicit E-** or **Q-vectors." Backends can (should) choose their own internal representation of `evector`s and `qvector`s. Optimized CPU backends, for example, do not form the entire `evector` or `qvector` for active inputs/outputs. Also, optimized CPU backends store a copy of the static passive inputs in the backend's preferred `qvector` ordering to improve performance on subsequent applications of the operator.

c) A future "todo" is to skip the memory movement in steps 1) and 2) above for  (See @jedbrown's comment). There are a few ways we can do this. It currently only slows the first application of a `CeedOperator` on the CPU side.

d) The behavior of multiple element basis actions can (should) be backend specific for performance.

The difference that seems to be causing the problems is with Identity `ElemRestriction`s. In CPU backends, Identity `ElemRestriction`s are used with the assumption that the `lvector` is in the canonical `evector` ordering, per b) above. In GPU backends, Identity `ElemRestriction`s are used with the assumption that the `lvector` is in a `qvector` format.

We need backends to continue to use internal `evector` and `qvector` layouts for performance. 

But, talking with Yohann, MFEM provides data to be used at the quadrature points in the layout `[component, element, node]`. This is not currently an `lvector` layout covered by the test suite for Identity `ElemRestriction`s. Conceptually, this operation is Identity `ElemRestriction` + `CEED_EVAL_NONE`. If we want to support the various possible permutations of `qvector`s as inputs/outputs (which makes sense for supporting all applications) then a struct like @nbeams proposed would be cleanest solution to me. We'd just have to be careful, as
i) `lvector`s only have two strides (`[component, node]` vs `[node, component]`) whereas `evector`s/`qvector`s have 3+ strides. This struct probably only makes sense for `evector`s and `qvector`s.
ii) We would need to think carefully about the `lmode` field, perhaps providing `CEED_LVEC_TRANSPOSE`, `CEED_LVEC_NOTRANSPOSE`, `CEED_EVEC_TRANSPOSE`, `CEED_EVEC_NOTRANSPOSE`, `CEED_QVEC_NEK`, `CEED_QVEC_MFEM`, `CEED_DECIDE` or the option of providing their own `CeedVectorLayout` struct. It would make sense to call `CeedElemRestrictionCreateIdentity` (probably want to rename if we are going to expand its meaning past `lvector` = `evector`) with an argument indicating the `lvector` is in one of the `CEED_EVEC*` or `CEED_QVEC` layouts above.

My brain hurts, but I think we're all closer to understanding each other now. Sorry for the wall of text; I was trying to be precise.

**Comment by jedbrown** [comment] 2020-01-18 21:48
I don't see why `[component, element, node]` to store externally-generated qdata is a problem.  Seems it works with Identity restriction, lmode=NOTRANSPOSE, and COLLOCATED.  This should be tested if it isn't currently.

**Comment by jeremylt** [comment] 2020-01-18 22:01
Yohann tested it and that layout isn't currently working for CPU. The CPU Identity restriction assumes [elem, comp, node] and doesn't have the ability to transpose comp and element like we would need. (CPU also doesn't currently do anything with the lmode for identity restrictions).

**Comment by jedbrown** [comment] 2020-01-18 22:22
Hmm, that seems funny. I see that with `comp` in the middle, it doesn't really make sense. FWIW, I think `[comp, element, node]` is not a great choice for CPU because it requires a lot more prefetch streams than would otherwise be needed.

As an alternative to having lots of constructors for "mathematical identity with different ordering conventions", perhaps we just specify restriction with indices and teach backends to optimize/compress sequences with certain properties (so it might not need to access the index data during `CeedOperatorApply`).

**Comment by YohannDudouit** [comment] 2020-01-21 21:21
@jedbrown This is something to keep in mind for the discussion tomorrow, `[comp, element, node]` is the best format for GPU (and worst(?) for CPU), and reciprocally `[element, node, comp]` is the worst format for GPU (and best(?) for CPU). This is why I also suggested that backends could be aware of the format they prefer (`GetPreferredLMode(Ceed ceed, int *lmode)`), in order to partially hide these technicalities to the user.

**Comment by jeremylt** [comment] 2020-01-21 21:28
To clarify, we use `[element, comp, node]` or `[block, comp, node, elementinblock]`. Our tensor contractions are only ever on `[comp, node]` or `[comp, node, elementinblock]`, with a loop over elements/blocks.

I don't think we need to have a function to advertise these backends technicalities to the user. I think we just need to tag evectors/qvectors with their layout and allow backends the reshuffle data to their preferred ordering and keep it in that ordering unless the user or another backend requests a different ordering.

**Closed** 2020-06-17 19:22 UTC
Labels: backend, design, enhancement, frontend, performance, testing
