### ISSUE TITLE
`CeedOperator` and `CeedElemRestriction` with Points Interfaces

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1328] opened 2023-09-08 18:07 UTC
We have an initial linking of the `DMSwarm` and `CeedBasisApplyAtPoints` in https://github.com/CEED/libCEED/pull/1284

Its time to start building our `CeedOperator` interface to support applying a full operator from Swarm to Plex or Plex to Swarm.

The overall flow I'm thinking of is as follows

~~Plex l-vec -> `CeedElemRestrictionApply` -> e-vec -> `CeedBasisApply` -> q-vec -> `CeedQFunctionApply` -> q-vec -> `CeedBasisApplyAtPoints` -> 'ragged' e-vec -> `CeedElemRestrictionApplyPoints` -> Swarm l-vec~~
Edit: That diagram is wrong

I think if we get the interface right, we can use a lot of the existing `CeedOperator` infrastructure, at least on the CPU side.

To make this work, we need

`CeedElemRestrictionCreatePoints()`
---

This restriction contains the information to gather/scatter a single element's points.

Proposed interfaces:
```C 
CEED_EXTERN int CeedElemRestrictionCreatePoints(Ceed ceed, CeedInt num_elem, CeedInt num_comp, CeedInt comp_stride, CeedSize l_size,
    CeedMemType mem_type, CeedCopyMode copy_mode, const CeedInt *offsets, CeedElemRestriction *rstr);
```
Where `offsets` is given by
```
total_num_cells
cell_0_start_index
cell_1_start_index
cell_2_start_index
...
cell_n_start_index
cell_n_stop_index
cell_0_point_0
cell_0_point_0
...
cell_n_point_m
```
Do we need the `comp_stride` variable? Is there any other sensible way to arrange the points except by keeping their data contiguous?

I'll have to think more about if we can do our 8 elem batching approach from `/cpu/self/ref/blocked` and `/cpu/self/opt/blocked` here, but it should be doable. Something like

```C
CEED_EXTERN int CeedElemRestrictionApplyBlock(CeedElemRestriction rstr, CeedInt block, CeedTransposeMode t_mode, CeedVector u, CeedVector ru,
    CeedRequest *request);
```

is straightforward for one element blocks but we'd have to think through the basis apply for 8 element blocks.

`CeedElemRestrictionGetElemOffset()`
---

We'll need some way to handle the ragged e-vec. This seems like the natural way to me

```C
CEED_EXTERN int CeedElemRestrictionGetElemOffset(CeedElemRestriction rstr, CeedSize elem, CeedSize *elem_offset);
```
Where we can get the `elem_offset` from the offsets array above as `offsets[elem + 1] - num_elem - 2`.

`CeedOperatorSetPointsField()`
---

~~We discussed this possible semantics for updating the operator when the swarm migrates. One option we have is to call `CeedOperatorSetPointsField` every time the swarm updates to reset the restriction and reference coordinates. We would want to check on the refcount so that we aren't mutating another reference and leading to surprising behavior.~~
Edit: unsure if this will be used - probably need completely different sort of CeedOperators
```C
CEED_EXTERN int CeedOperatorSetPointsField(CeedOperator op, const char *field_name, CeedElemRestriction r, CeedBasis b, CeedVector x_ref, CeedVector v);
```

---

I suspect I'm missing some stuff here, but this can get the conversation started.

**Comment by knepley** [comment] 2023-09-08 18:34
@jeremylt Note that I just put in an interface for conservative projection, https://gitlab.com/petsc/petsc/-/merge_requests/6856, and it would be great if you could reproduce those operations in CEED.

**Comment by knepley** [comment] 2023-09-08 18:34
Also, Danny has an example that does Landau Damping, Swarm ex9. That would be a great eventual target.

**Comment by jeremylt** [comment] 2023-09-08 18:47
For context, our current targets are first a simple projection problem and then building iMPM in Ratel.

**Comment by knepley** [comment] 2023-09-08 19:50
Good, then the conservative projection is what you want I think

**Comment by jeremylt** [comment] 2023-09-08 20:58
The more I look at this, the more I think I wrote `CeedBasisApplyAtPoints` "backwards" with respect to how a normal operator works.

For a normal `CeedBasisApply`, when we `CEED_NOTRANSPOSE` we go nodes -> quadrature space and `CEED_TRANSPOSE` goes quadrature space -> nodes.

For a `CeedBasisApplyAtPoints`, when we `CEED_NOTRANSPOSE` we go nodes -> points and `CEED_TRANSPOSE` goes points -> nodes.

BUT, I think it would work more naturally with the operator above if

For a `CeedBasisApplyAtPoints`, when we `CEED_NOTRANSPOSE` we go points -> quadrature space and `CEED_TRANSPOSE` goes quadrature space -> points.

Objections to flipping to this new convention @zatkins-dev and @jedbrown?

**Comment by jedbrown** [comment] 2023-09-08 21:03
What do you mean "quadrature space"? We're going to have a qfunction run at particles so I think of the particles as being "inside the sandwich", i.e., the quadrature space. I don't think there is a direct map from particles to Gauss quadrature, as that normally involves an FE projection first (which for continuous spaces, depends on contributions from outside the element).

**Comment by jeremylt** [comment] 2023-09-08 21:09
Ah, you are thinking of a QFunction as not actually being a "quadrature space function" anymore? I was thinking we'd use the quadrature space from the background mesh so I though the flow would be 1) project points to mesh 2) compute quantities of interest oh the mesh quadrature space 3) interpolate those quantities of interest to the points

If we don't have a true quadrature space but instead are using the points in place of a quadrature space, how are we building the mass matrix for the projection?

**Comment by knepley** [comment] 2023-09-08 21:26
Ah, we explain that here: https://arxiv.org/abs/2205.06402. There is an analagous operator to mass matrix.

**Comment by jeremylt** [comment] 2023-09-08 21:30
Thanks for the link. This looks much more involved than a simple modification to our existing infrastructure like I thought we were planning.

**Comment by jedbrown** [comment] 2023-09-08 21:53
So we need to compute strain tensors at particles because materials only exist at particles, thus constitutive relations can only be evaluated at particles. For a SNES residual, we'll have a qfunction at particles that takes particle data and gradients of the FE field (SNES state vector), project constitutive quantities into an FE space, and apply an operator on Gauss quadrature points. The Jacobian (or approximate Jacobian sufficient for multigrid) will live entirely at Gauss quadrature points.

**Comment by jeremylt** [comment] 2023-09-08 22:12
Ok, I'll do more reading. At this point, I'm not sure I'll understand these new types of CeedOperator enough to have something working correctly at the end of the month. It seems like eventually we'll have 3 new operators

1) mesh to points where qvec == evec == lvec?
2) points to mesh quadrature space?
3) mesh quadrature space to mesh quadrature space that doesn't use mesh nodes?

**Comment by jedbrown** [comment] 2023-09-08 22:54
I don't know what is meant by "mesh quadrature space", but the particle operators will all have the form $E_o^T B_o^T D B_i E_i$ where one of the input or output bases can be an identity (so the results are collocated at particles), otherwise the inputs/outputs are FE fields. Everything involving particles is separate from Gauss quadrature points (must move though standard FE fields to go between particles and quadrature). SNES residual will have both $B_i$ and $B_o$ acting on FE fields. In particular, $B_i$ will compute a gradient of displacement (so strain can be defined at particles) and $B_o$ will be interpolation of a constitutive model output. Given that nodal field, there will be a standard FE L^2 projection or differential filter (still close to a mass matrix) and likely another standard field qfunction -- both of these have no reference to particles.

When a time step is accepted, there will be an operator that evaluates field data at particles and increments the stored particle data ($E_o$ will be identity).

**Comment by zatkins-dev** [comment] 2023-09-11 22:31
From our conversation today @jedbrown, we will want the following flavors of operator for MPM:
 - FE Field (grad U input) -> particles (eval constitutive relations using particle fields) -> FE Field (projected stress or equiv, e.g. effective viscocity)
   - This is like a normal `CeedOperatorApply`, except we use particles instead of quadrature points and have particle fields as passive inputs
 - FE Field (projected stress) -> gauss qpts (evaluate grad(v) : s) -> FE Field (displacement)
   - This is essentially a normal `CeedOperatorApply`, just using the projected field computed with the above operator as the active input
 - FE Field (displacement) -> particles (update particle positions and stored variables) -> Empty Output FE Field

In general, our operators should have:
 - Inputs:
   - <= 1 Active FE Field
   - 1 Set of particles
   - Passive inputs
 - Outputs
   - <= 1 Active FE Field
   - 1 Set of particles (maybe with changed internal fields)
   - Passive outputs

The output FE fields are computed using a projection, either by using a lumped or consistent mass matrix.
Stored data (constitutive properties, accumulated strain, plastic damage, etc.) should only be defined at particles. 

ElemRestriction for particles (and DMSwarmMigrate) is only updated once per timestep (i.e. only semi-implicit). We use the initial configuration of particles to determine the displacement, then update once the timestep is accepted. 

@jedbrown please let me know if any of that is incorrect.

**Comment by jeremylt** [comment] 2023-09-11 22:36
I logged on but it looked like the Zoom wasn't in use.

---

How can we do a projection *inside* of our CeedOperator?

I think overall the core of my confusion is on how we can sensibly do "quadrature" on the particles space. I though that one of the benefits to the background mesh in MPM is that it gives a place where quadrature works exactly as we expect?

**Comment by zatkins-dev** [comment] 2023-09-11 23:43
> I logged on but it looked like the Zoom wasn't in use.
> 
> 
> 
> ---
> 
> 
> 
> How can we do a projection *inside* of our CeedOperator?
> 

So I think this is the `CeedOperatorApplyAtPoints` transpose, i.e. particles to FE space. @jedbrown can correct me if I'm wrong here. 

> 
> I think overall the core of my confusion is on how we can sensibly do "quadrature" on the particles space. I though that one of the benefits to the background mesh in MPM is that it gives a place where quadrature works exactly as we expect?
> 
> 

If I understand correctly, we shouldn't think of this as "doing quadrature at particles", but rather evaluating constitutive relations at particles (the only place where material properties are defined) and using that to get the projected stress field at nodes. 

We still use a quadrature space on the mesh to integrate with our test functions, which is where the regularity of the quadrature points should actually matter. 

> ---
> 
> 
> 
> > When a time step is accepted, there will be an operator that evaluates field data at particles and increments the stored particle data ($E_o$ will be identity).
> 
> 
> 
> Points are not going to stay contiguous in memory by cell, so I don't think we can rely upon $E_o$ always being an identity operator. In general it will have to be a permutation operator, right?

I would agree with that

**Comment by jeremylt** [comment] 2023-09-11 23:47
It sounds like I have a lot of confusion over the terminology.

I wouldn't have thought that just applying the transpose basis alone is called a 'projection'.

**Comment by jedbrown** [comment] 2023-09-12 03:18
1. Projection (in the sense of solving with a mass matrix or similar) isn't happening inside a QFunction, but we do have a weak form something like $\int v \delta(x - p) S_p(E; \texttt{particledata})$, where $S_p$ is evaluated at particles and $\delta$ is the Dirac delta function. This is the lumping scheme used in pTatin to project particles into the FE space. Note that the denominator of (18) is purely geometric -- there are other ways to normalize/compute particle weights, but they'll have similar structure.

![image](https://github.com/CEED/libCEED/assets/3303/3b9a3bc5-1db6-4f7a-872b-38509d8b99a3)

2. I think that's a choice we can make -- whether to sort by cell or do all operations through the permutation operator. We discussed this earlier and I think settled on using the permutation, so yes.

**Comment by jedbrown** [comment] 2023-09-13 15:55
We're going to need new restrictions and new `CeedVector` lengths (assuming we keep using `CeedVector` to hold particle data, which seems appropriate since eventually they'll be able to live on GPU). I think we can just recreate that stuff once per time step. Within a time step, I think the only stored quantities that change will be vectors in the FE space (SNES residual, Krylov vectors), so that fits our standard FE assumptions. The SNES residual will visit particles, but not store anything there.

**Comment by zatkins-dev** [comment] 2023-09-13 20:58
> We're going to need new restrictions and new `CeedVector` lengths
For clarity, I'm using the `CeedOperator_Ref` implementation as a reference point to think about what changes will be needed.
I think that if we can reset the element restrictions (and set the `op->is_backend_setup` flag back to false at the same time), then the element vectors should be reallocated correctly automatically. We shouldn't need to change the full particle field vector, since our element restriction will do the required permutation/restriction of particles into their respective elements.

**Comment by jeremylt** [comment] 2023-09-13 21:03
We'll need to change the particle vector because our points will migrate so the local vector length with change.

**Comment by zatkins-dev** [comment] 2023-09-13 21:05
Ah, I see. I wasn't thinking about that.

**Comment by jeremylt** [comment] 2023-09-14 20:57
See #1333, I think if we like that we can merge it and add it to #1284

**Comment by zatkins-dev** [comment] 2023-10-21 20:29
I've been thinking more about this design, and I have a few observations that I want to write down and may be useful. 

## Operator Interface Design
It is useful to think about `CeedOperator` interface design in terms of where the `CeedQFunctionApply` takes place, or in other words, what the Q-vectors refer to. For normal operators, the Q-vectors are field values at quadrature points and the `CeedQFunctionApply` takes place at the quadrature points. For our "points" `CeedOperator`, the Q-vector will be the field values at each point in the element. I've come up with a few design options for how we think about the input and output fields.

### Option 1: Simplest implementation
This option leaves the existing `CeedOperator` interface unchanged and adds a new `CeedOperatorPoints` interface.

A `CeedOperatorPoints` will have input and output fields exclusively defined at points. This would be very simple to implement, as it would be decoupled from the mesh FE space. That is, evaluating the `CeedOperatorPointsApply` would require applying the qfunction at each point, which could be done by element or just by arbitrary groupings of points (the latter may be more parallelizable). 

The mesh-to-points and points-to-mesh utilities from the `petsc-dmswarm` example would then be used to map between points/mesh vectors to permit use of both types of operators. Or, these utilities could be a special case of operators with identity Q functions for consistency and ease of use. 

Advantages:
1. Simpler to implement because it doesn't require using the mesh-to-points methods inside of the `CeedOperator`, which can get quite messy due to needing multiple restrictions (one for points, one for mesh) for each field defined in the mesh
2. More flexibility in terms of how the projection is performed without making the operator interface more complicated
3. Minimal changes to existing interface
4. Potentially better parallelism for operations at points (although the conversion will still require some care)

Disadvantages:
1. Higher storage cost due to computing full L-vectors for fields, then converting
2. Requires several specialized operator types, especially if mapping between points and mesh is done with new operator types.
3. On the other hand, this implementation would require more operators overall. For example, consider this "operator" from above:
> FE Field (grad U input) -> particles (eval constitutive relations using particle fields) -> FE Field (projected stress or equiv, e.g. effective viscocity)

This would require three operators/converters:
  - Interpolate $\nabla U$ from mesh to points.
  - `CeedOperatorPoints` with active points input of $\nabla U$, passive points inputs of history variables, etc., active points output of stress and a QFunction which evaluates the constitutive model.
  - Project stress at points from points to mesh.

### Option 2: Integrate mesh-to-points into the operator
This option would allow for `CeedOperator`s to internally convert mesh fields to points fields using essentially the same process as in `DMSwarmInterpolateFromCellToSwarm_Ceed`. 

Advantages:
1. A single operator could use mesh and points inputs, so long as the QFunction is evaluated at points and the output is at points. This removes the need to store full points vectors for mesh fields.
2. Possibly simpler for users, since there would be fewer conversion.

Disadvantages:
1. Any mesh field would need an element restriction for its corresponding points field, which would either need to be created by the `CeedOperator` or passed in through a new interface.
2. The `CeedOperator` would likely need to store the `offsets` and `x_ref` data, since otherwise creating those element restrictions would be difficult.
4. Adds a lot of complexity when applying the operator, as each field would have to be converted within the operator.
5. Doesn't really simplify many of the issues with option 1, as we would still have to use an external projection utility to go from points to mesh.

### Option 3: Implement everything into the operator
This would be option 2, but with the points-to-mesh conversion implemented in the operator as well.

Advantages:
1. In theory, would allow inputs and outputs to be points or mesh fields, regardless of the action of the QFunction. This would certainly be the most flexible for usage.
2. Less operators, since conversion would be built in.

Disadvantages:
1. How do we do points-to-mesh projection inside of an operator apply?
2. Lots of opaque restrictions that would need to be stored inside the operator with their state correctly maintained. This seems very difficult for arbitrary numbers of fields.
3. We would likely need some `CeedOperatorSetFieldAtPoints` interface to manage those element restrictions and such.

**Comment by jeremylt** [comment] 2023-10-21 20:58
I think we will have something like your option 1, but the inputs and outputs could be at points or the mesh. The 'quadrature' space is the points. Basis operations from/to the mesh would use BasisApplyAtPoints. Basis operations to/from the swarm would be only be CEED_EVAL_NONE. 

We would end up creating an Opt version of this approach to avoid the lvecs, like with our current operators.

**Comment by jeremylt** [comment] 2023-10-23 16:11
This is the sort of user facing interface I was thinking of.

Here would be the projection operator, so mesh input, mesh output, 'quadrature' on the swarm
```C
CeedQFunctionCreateInterior(ceed, 1, mass, mass_loc, &qf);
CeedQFunctionAddInput(qf, "u", 1, CEED_EVAL_INTERP);
CeedQFunctionAddOutput(qf, "v", 1, CEED_EVAL_INTERP);

CeedOperatorCreateAtPoints(ceed, qf, CEED_QFUNCTION_NONE, CEED_QFUNCTION_NONE, &op);
CeedOperatorSetField(op, "u", elem_restriction_u_mesh, basis_u, CEED_VECTOR_ACTIVE);
CeedOperatorSetField(op, "v", elem_restriction_u_mesh, basis_u, CEED_VECTOR_ACTIVE);
CeedOperatorAtPointsSetPoints(op, elem_restriction_x_points, x_points_loc);
```
This would be an operator from mesh to points, so mesh input, swarm output
```C
CeedQFunctionCreateInterior(ceed, 1, interp, interp_loc, &qf);
CeedQFunctionAddInput(qf, "u_mesh", 1, CEED_EVAL_INTERP);
CeedQFunctionAddOutput(qf, "u_points", 1, CEED_EVAL_NONE);

CeedOperatorCreateAtPoints(ceed, qf, CEED_QFUNCTION_NONE, CEED_QFUNCTION_NONE, &op);
CeedOperatorSetField(op, "u_mesh", elem_restriction_u_mesh, basis_u, CEED_VECTOR_ACTIVE);
CeedOperatorSetField(op, "u_poins", elem_restriction_u_points, CEED_BASIS_NONE, CEED_VECTOR_ACTIVE);
CeedOperatorAtPointsSetPoints(op, elem_restriction_x_points, x_points_loc);
```

**Comment by zatkins-dev** [comment] 2023-10-23 17:06
To make sure that I understand correctly, would this be the appropriate way to set up this operator:
> FE Field (grad U input) -> particles (eval constitutive relations using particle fields) -> FE Field (projected stress or equiv, e.g. effective viscocity)

```c
CeedQFunctionCreateInterior(ceed, 1, compute_stress, compute_stress_loc, &qf);
CeedQFunctionAddInput(qf, "grad u", num_comp_u * dim, CEED_EVAL_GRAD);
CeedQFunctionAddInput(qf, "point data", num_point_data_components, CEED_EVAL_NONE);
CeedQFunctionAddOutput(qf, "stress", num_comp_u * dim, CEED_EVAL_GRAD);

CeedOperatorCreateAtPoints(ceed, qf, CEED_QFUNCTION_NONE, CEED_QFUNCTION_NONE, &op);
CeedOperatorSetField(op, "u", elem_restriction_u_mesh, basis_u, CEED_VECTOR_ACTIVE);
CeedOperatorSetField(op, "point data", elem_restriction_point_data, CEED_BASIS_NONE, point_data_loc);
CeedOperatorSetField(op, "stress", elem_restriction_u_mesh, basis_u, CEED_VECTOR_ACTIVE);
CeedOperatorAtPointsSetPoints(op, elem_restriction_x_points, x_points_loc);
```
Where `point_data_loc` has all of the required state input defined in a particle field. Behind the scenes, the operator would handle computing $\nabla u$ at particles, evaluating the Q function at particles, then projecting the output back to the mesh. I'm not sure on the output still...I'm not convinced whether this should be `CEED_EVAL_GRAD` or `CEED_EVAL_INTERP` with a different `DM`/basis and restriction.

**Comment by zatkins-dev** [comment] 2023-10-23 17:13
Fair enough, then the `stress` field would need to be `CEED_EVAL_INTERP` with its own `DM`, restriction, and basis.

**Comment by jeremylt** [comment] 2023-10-23 17:14
It wouldn't need to be a separate DM necessarily, but at least a separate DM field

**Comment by jedbrown** [comment] 2023-10-24 04:01
> `CEED_EVAL_GRAD` is not currently a valid transpose eval mode for `CeedBasisApplyAtPoints`

We're going to need to add this to do naive MPM (i.e., just use particles as integration points for the momentum balance weak form). It won't be used if/when we move to a material projection approach.

**Closed** 2023-12-15 19:13 UTC
Labels: enhancement, design, interface
